package com.bc.revan.Entities.Enums;

public enum EnumForTimeInterval {
	ZERO_TO_FIFTEEN,
	SIXTEEN_TO_THIRTY,
	THIRTY_ONE_TO_FORTY_FIVE,
	FORTY_SIX_TO_SIXTY,
	SIXTY_ONE_TO_SEVENTY_FIVE,
	SEVENTY_SIX_TO_NINETY,
	NINETY_ONE_TO_ONE_HUNDRED_FIVE,
	ONE_HUNDRED_SIX_TO_ONE_TWENTY
}
